// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hetznerdns
{
    public static class GetZone
    {
        /// <summary>
        /// ## # hetznerdns.Zone Data Source
        /// 
        /// Provides details about a Hetzner DNS Zone.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Hetznerdns = Pulumi.Hetznerdns;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var zone1 = Output.Create(Hetznerdns.GetZone.InvokeAsync(new Hetznerdns.GetZoneArgs
        ///         {
        ///             Name = "zone1.online",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetZoneResult> InvokeAsync(GetZoneArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZoneResult>("hetznerdns:index/getZone:getZone", args ?? new GetZoneArgs(), options.WithDefaults());

        /// <summary>
        /// ## # hetznerdns.Zone Data Source
        /// 
        /// Provides details about a Hetzner DNS Zone.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Hetznerdns = Pulumi.Hetznerdns;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var zone1 = Output.Create(Hetznerdns.GetZone.InvokeAsync(new Hetznerdns.GetZoneArgs
        ///         {
        ///             Name = "zone1.online",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetZoneResult> Invoke(GetZoneInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZoneResult>("hetznerdns:index/getZone:getZone", args ?? new GetZoneInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZoneArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the DNS zone to get data from.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetZoneArgs()
        {
        }
    }

    public sealed class GetZoneInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the DNS zone to get data from.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetZoneInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZoneResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int Ttl;

        [OutputConstructor]
        private GetZoneResult(
            string id,

            string name,

            int ttl)
        {
            Id = id;
            Name = name;
            Ttl = ttl;
        }
    }
}
