# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_zone import *
from .provider import *
from .record import *
from .zone import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_hetznerdns.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_hetznerdns.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "hetznerdns",
  "mod": "index/record",
  "fqn": "pulumi_hetznerdns",
  "classes": {
   "hetznerdns:index/record:Record": "Record"
  }
 },
 {
  "pkg": "hetznerdns",
  "mod": "index/zone",
  "fqn": "pulumi_hetznerdns",
  "classes": {
   "hetznerdns:index/zone:Zone": "Zone"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "hetznerdns",
  "token": "pulumi:providers:hetznerdns",
  "fqn": "pulumi_hetznerdns",
  "class": "Provider"
 }
]
"""
)
