// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("hetznerdns");

/**
 * The API access token to authenticate at Hetzner DNS API.
 */
export declare const apitoken: string | undefined;
Object.defineProperty(exports, "apitoken", {
    get() {
        return __config.get("apitoken");
    },
    enumerable: true,
});

