// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getZone";
export * from "./provider";
export * from "./record";
export * from "./zone";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { Record } from "./record";
import { Zone } from "./zone";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "hetznerdns:index/record:Record":
                return new Record(name, <any>undefined, { urn })
            case "hetznerdns:index/zone:Zone":
                return new Zone(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("hetznerdns", "index/record", _module)
pulumi.runtime.registerResourceModule("hetznerdns", "index/zone", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("hetznerdns", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:hetznerdns") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
